version: "2"

run:
  timeout: 5m
  tests: true

linters:
  exclusions:
    rules:
      - linters:
          - gocritic
        path: internal/smc/smc.go
  enable:
    - errcheck
    - govet
    - goconst
    - gocritic
    - gocyclo
    - ineffassign
    - staticcheck
    - unused
    - revive
    - unconvert
    - tparallel
    - whitespace
  settings:
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - performance
      settings:
        captLocal:
          paramsOnly: true
        rangeValCopy:
          sizeThreshold: 32
    gocyclo:
      min-complexity: 10

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: false
    goimports:
      local-prefixes:
        - github.com/peterneutron/powerkit-go

issues:
  max-same-issues: 0
