# This workflow runs the golangci-lint linter on the codebase.
# It helps to ensure code quality and consistency.
name: Lint

on:
  # Run this workflow on pushes to the main branch and on any pull request.
  push:
    branches: [ main ]
  pull_request:
    branches: [ "main" ]

jobs:
  golangci:
    name: lint
    # This job runs on the latest version of macOS, which is crucial for
    # your Cgo-based project that depends on macOS frameworks.
    runs-on: macos-latest
    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up the Go environment
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5' # Use your project's Go version
          cache: true

      # Step 3: Run the golangci-lint action
      # This action automatically downloads the linter, caches it,
      # and runs it using our .golangci.yml configuration.
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          # Required: the version of golangci-lint.
          # Using a specific version is recommended for reproducible builds.
          version: v2.3.1

          # Optional: show only new issues if it's a pull request.
          # This is great for incrementally improving a legacy codebase.
          only-new-issues: false
